### ISSUE TITLE
wayfarer@6 no longer uses symbols

### ISSUE THREAD

**Issue by terinjokes** [yoshuawuyts/wayfarer-to-server#3]
wayfarer no longer uses symbols, but this project still looks for the symbol previously exposed.

**Comment by yoshuawuyts** [comment]
oh crap, yeah I should deprecate this project - never came around to writing the server router that we deserver - might do that soon

**Comment by yoshuawuyts** [comment]
pushed a deprecation notice to the readme

**Comment by terinjokes** [comment]
Sad day.

**Comment by yoshuawuyts** [comment]
better day https://github.com/yoshuawuyts/server-router
